### ISSUE TITLE
changeDeviceId(null) throws IllegalStateException

### ISSUE THREAD

**Issue by renaudcerrato** [Countly/countly-sdk-android#102]
The `changeDeviceId()` documentation is really scarce. Looking at the sample, you're setting the device id to null:

https://github.com/Countly/countly-sdk-android/blob/5cc8dbed11e9daf18e9065a0831c4b1bdfe7d29d/app/src/main/java/ly/count/android/demo/ActivityExampleDeviceId.java#L44

But that would throw an `IllegalStateException` on 19.09: 

https://github.com/Countly/countly-sdk-android/blob/5cc8dbed11e9daf18e9065a0831c4b1bdfe7d29d/sdk/src/main/java/ly/count/android/sdk/Countly.java#L837

What's the recommended way to close that session when the user logout, if we're NOT using OpenUUID (or advertising id) ? Shall we use `changeDeviceId(DEVELOPER_SUPPLIED, null)` or `enableTemporaryIdMode()` instead?

**Comment by ArtursKadikis** [comment]
Please use the community forum to ask usage questions. If that same user is going to log in (single user, single device) then you probably don't want to change the id on logout. IF you really want to then you should not merge id on login and on logout you set the previous key. If you do change your id on logout and don't merge it into a "known" one, it will only create additional users. For changing id without merging you should then use 'changeDeviceId(DEVELOPER_SUPPLIED, yourCreatedId)'.
