### ISSUE TITLE
Cancel event ?

### ISSUE THREAD

**Issue by ryancrunchi** [Countly/countly-sdk-android#106]
### Expected Behavior
iOS SDK provides a way to cancel an event after `startEvent`.
I can't find a similar method in Android SDK.
Is there an official way of doing it, or a workaround ?

### Possible Solution
Add a method to cancel a timed event, as in iOS SDK.

### Your Environment
* Countly Android SDK version
19.09

**Comment by ArtursKadikis** [comment]
Call will be added in the next release

**Comment by ArtursKadikis** [comment]
Added in 20.04
