### ISSUE TITLE
Dependency injection / module architecture broke all thread safety

### ISSUE THREAD

**Issue by aimkey** [Countly/countly-sdk-android#118]
Thread safety across the SDK was lost when synchronized methods from the old Countly god-object were moved into their respective modules. These methods are now synchronized with different locks (their interface, an inner class of the module), and are therefore no longer thread safe. Thread safety can be regained trivially by using the ```Countly``` instance passed to each module as the module and interface wide lock.

eg. 

```
public class ModuleViews extends ModuleBase {
    @Inject Countly _cly;

    public class Views {
        public synchronized Countly recordView(String viewName) {
            // method contents...
        }
    }
}
```

should become

```
public class ModuleViews extends ModuleBase {
    @Inject Countly _cly;

    public class Views {
        public Countly recordView(String viewName) {
            synchronized(_cly) {
                // method contents...
            }
        }
    }
}
```

**Comment by ArtursKadikis** [comment]
Hello. Just a fyi, this commit should fix this issue:
https://github.com/Countly/countly-sdk-android/commit/10631dea6cb2b72138507d384ce9c6f7b62aa8e3

**Comment by ArtursKadikis** [comment]
Fix released
