### ISSUE TITLE
Lint Check Fails For CertificateTrustManager Implementation

### ISSUE THREAD

**Issue by keremkusmezer** [Countly/countly-sdk-android#123]
Lint fails with the following error on library usage check for the application

checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers

This check looks for X509TrustManager implementations whose `checkServerTrusted` or `checkClientTrusted` methods do nothing (thus trusting any certificate chain) which could result in insecure network traffic caused by trusting arbitrary TLS/SSL certificates presented by peers

TrustAllX509TrustManager

### Expected Behavior
Lint should succeed without creating the error. 
 

### Current Behavior
Google Play has started scanning app code for disabling certificate checks and will reject it whether that code is reachable or not. All apps should use Proguard for for release build but not all do. Not to mention that it depends on details of the implementation whether Produard will detect the code as unused.

### Possible Solution
Either implement the method checkClientTrusted at the CertificateTrustManager or change the Certificate Pinning logic

### Your Environment
* Countly 20.04.2
* Android 9
* Xiaomi Mi 8

**Comment by iartem** [comment]
Thanks for that one! From how others fix it, the commit should resolve it, but feel free to reopen in case it's not
