### ISSUE TITLE
Custom Properties cant be deleted.

### ISSUE THREAD

**Issue by jon0hopper** [Countly/countly-sdk-android#124]
I want to be able to delete a custom property I have set on a user, it that property is no longer relevant.

### Expected Behavior
As per the API;  https://api.count.ly/reference#section-user-details  "If you set value as null, you will delete the property."

however, currently in ly.count.sdk.internal.UserEditorImpl, if the value is null it is deleted from the request, and not sent to the countly server.
              
### Possible Solution
Change  ly.count.sdk.internal.UserEditorImpl.perform  so that if null is passed in for a custom property, that null is  kept, and sent to the api, so that the property can be removed.

>   default:
>                     if (value == null || value instanceof String || value instanceof Integer || value instanceof Float || value instanceof Double || value instanceof Boolean
>                             || value instanceof String[] || value instanceof Integer[] || value instanceof Float[] || value instanceof Double[] || value instanceof Boolean[] || value instanceof Object[]) {
>                         if (!changes.has(CUSTOM)) {
>                             changes.put(CUSTOM, new JSONObject());
>                         }
>                         changes.getJSONObject(CUSTOM).put(key, value);
>                         **if (value == null) {
>                             user.custom.remove(key);**
>                         } else {
>                             user.custom.put(key, value);
>                         }
>                     } else {
>                         L.wtf("Type of value " + value + " '" + value.getClass().getSimpleName() + "' is not supported yet, thus user property is not stored");
>                     }

### Your Environment
I am using 
core-19.09-sdk2-rc.jar
java-19.09-sdk2-rc.jar

**Comment by ArtursKadikis** [comment]
Hello, this should be solved now

**Comment by jon0hopper** [comment]
Oh excellent. I left the company where I had the problem 2 years ago ..but nice to see my change go in!--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 25/01/2024, 20:33 "Artūrs Kadiķis" ***@***.***> wrote:

   
  Hello, this should be solved now
