### ISSUE TITLE
Single Activity Architecture and Countly?

### ISSUE THREAD

**Issue by AnneSchu** [Countly/countly-sdk-android#125]
Our customer wants to use Countly in a "Single-Activity-Design"-Application and I am wondering how this can be implemented. Our Problem is that the initialization of Countly should be done after login and therefore after onStart() of the only (Main)Activity.

### Expected Behavior
I want to be able to start Countly independently from the MainActivitiy.

### Current Behavior
At the moment I start Countly right after initialitation which happens after login. However, the counter of the activities is not correct if the app changes its state. (There are even negative counts...)
onStop cannot be used as it results in Exceptions. Hence, the sessions cannot be tracked correctly which is our main issue.

### Possible Solution
One possible solution would be a close support with the opportunity to talk to someone in order to discuss the specifics of our setup. We use Counlty Enterprise Edition. However, as a subcontractor we have no direct contact to the support yet... Do you have a hint how we can change that?

### Your Environment
* Countly Android SDK version: 20.11.0
* Your Android version: 10 (API 29)
* Your device: Xiaomi Poco X3

**Comment by ArtursKadikis** [comment]
Hello.
The SDK is currently designed around being initialised in the Application class or at least in the "onCreate" callback of a Activity.

There aren't really any reasons why the SDK would not work with a single activity app, though view tracking will be slightly more complicated as it would have to be done manually.

A thing you could try is manual session control. This way it would be decoupled from the activity lifecycle.

Is there a specific reason why you want to initialise the SDK after login? Why not collect the data also before it?

For access to direct support you would probably have to talk with the ones who you are a subcontractor of. As the would have to put in in contact with support. If you have some questions, you could ask hello@count.ly .

**Comment by AnneSchu** [comment]
Hello and my thanks for your prompt and helpful answer,
the reason for our setup is security. I have implemented manual view tracking and session management. After a first glance it seems to work. We'll see how it goes...
Thank you also for your advice about the support. This was very helpful!
