### ISSUE TITLE
Events Segmentation Issue Not getting complete data 

### ISSUE THREAD

**Issue by rahulr4** [Countly/countly-sdk-android#135]
Hi,
I am passing all these data in the segmentation parameter of the recordEvent method but when i am checking on the console, i see always only 5 of these values.
`val hashmap = HashMap<String, String>()
                hashmap["loginStatus"] = "No"
                hashmap["category"] = "Search"
                hashmap["deviceId"] = "74fae12e689a18c2"
                hashmap["action"] = "SearchType"
                hashmap["lastThreeSearches"] = "No"
                hashmap["city"] = "Delhi"
                hashmap["positionInEtype"] = "2"
                hashmap["section"] = "All"
                hashmap["userId"] = "4919999"`

Countly.sharedInstance().events().recordEvent(key, newMap);

On the console:
`{
   "app_key": "Rahul_Android",
   "hour": "15",
   "dow": "1",
   "events": [
      {
         "key": "[CLY]_view",
         "count": "1",
         "timestamp": "1636971932708",
         "hour": "15",
         "dow": "1",
         "segmentation": {
            "name": "HomePage"
         },
         "sum": "0"
      },
      {
         "key": "[CLY]_view",
         "count": "1",
         "timestamp": "1636972057507",
         "hour": "15",
         "dow": "1",
         "segmentation": {
            "name": "D_You"
         },
         "sum": "0"
      },
      {
         "key": "MYTESTSERACH",
         "count": "1",
         "timestamp": "1636972058190",
         "hour": "15",
         "dow": "1",
         "segmentation": {
            "deviceId": "74fae12e689a18c2",
            "userId": "4919999",
            "city": "Delhi",
            "lastThreeSearches": "No",
            "category": "Search",
            "action": "SearchType"
         },
         "sum": "0"
      }
   ],
   "sdk_version": "16.12.3",
   "sdk_name": "java-native-android",
   "device_id": "1de50d6294b196d1",
   "checksum": "8628107250165465fc6d2d5dbf885426f7c39848",
   "metrics": {
      "_device": "EB2101",
      "_os": "Android",
      "_os_version": "11",
      "_carrier": "airtel",
      "_resolution": "1080x2156",
      "_density": "other",
      "_locale": "en_US",
      "_app_version": "10.10.4"
   },
   "serverTimestamp": 1636972133980
}`

as you can see the event "MYTESTSERACH" has 9 values but i am getting only 5

**Comment by ArtursKadikis** [comment]
Hello, please enable logging in the SDK and send the generated SDK logs. You would send the logs from the moment that the SDK is initialized, to slightly after you have recorded your event.

**Comment by rahulr4** [comment]
Fixed at my end
