### ISSUE TITLE
Push notification crash on Android 12

### ISSUE THREAD

**Issue by alirezanazari** [Countly/countly-sdk-android#137]
There is a new bug in the latest version of Countly SDK for Android and it crashes just on Android 12.

Stacktrace: 
java.lang.RuntimeException: Unable to start receiver ly.count.android.sdk.messaging.CountlyPush$NotificationBroadcastReceiver: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.samanpr.blu (pid=_, uid=__) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.

API Changes:
https://developer.android.com/about/versions/12/behavior-changes-all?hl=fr#close-system-dialogs

**Comment by ArtursKadikis** [comment]
Hello, this issue should be fixed in this release:
https://github.com/Countly/countly-sdk-android/releases/tag/20.11.12
