### ISSUE TITLE
Add a way to stop the service - like stop()

### ISSUE THREAD

**Issue by AshStefanOltmann** [Countly/countly-sdk-android#138]
I want to stop the statistic sending as soon as the user opts out of this.

The Java SDK has a dedicated `stop()` method to shut down the engine.

The Android SDK has no such option. I tried calling `onStop()` which seems to signal something, but does not stop sending messages.

I also tried calling `Countly.sharedInstance().consent().removeConsentAll()` after I configured `config.setRequiresConsent(true)`, but this is not effective until the whole app is restarted.

So I currently see no way to stop the sending of anaytics once `Countly.sharedInstance().init(config)` is called.

**Comment by iartem** [comment]
Please refer to [this method](https://github.com/Countly/countly-sdk-android/blob/master/sdk/src/main/java/ly/count/android/sdk/Countly.java#L727-L734)

**Comment by AshStefanOltmann** [comment]
> Please refer to [this method](https://github.com/Countly/countly-sdk-android/blob/master/sdk/src/main/java/ly/count/android/sdk/Countly.java#L727-L734)

Thank you! :)

One additional question: Once it's halted, how can I turn it on again?

I have a switch in my settings and stopping using `halt()` works, but if I do a new `Countly.sharedInstance().init(config)` it does not come back.

I also tried `Countly.sharedInstance().sessions().beginSession()`, but I think this is only effective if I have manual session tracking in general.

Only a restart of the app brings it back to life. So it looks like `halt()` destroys that for runtime.

Is this intented or is it a bug? How can I continue the logging?

I just notice it also doesn't work on the Java SDK.

**Comment by ArtursKadikis** [comment]
"halt" is quite a desctructive stopping approach, and it is not intended for stopping and then restarting the SDK.

"onStop" is for interacting with the Activity lifecycle, and "sessions().beginSession()" is only for manual session tracking.

The closest thing to an "on" and "off" switch would be giving/removing consent. Removing all consent should prohibit any additional information to be recorded, though it will still attempt to send all previously recorded information.

**Comment by AshStefanOltmann** [comment]
@ArtursKadikis Thank you for that overview.

Watching with requestbin.com what the SDK actually sends I noticed that even after removing all consent by calling `removeConsentAll()` the requests continue until restart of the app.

Consider a user of the app never actually quits it but rather only puts it to background this will continue all the time even if the user does not want that.

**Comment by ArtursKadikis** [comment]
" the requests continue until restart of the app"
If those would be newly generated requests/events then that would be a bug. So it would depend on for how long you were running the app afterwards.

Could you please enable logging in the SDK, execute your in app actions to remove all consent, perform some other actions that would previously generate requests/events and then send that log to me? The log would be found in logcat and the logs would use the tag "Countly". Please send all logs from the moment that the SDK is initialized.

**Comment by AshStefanOltmann** [comment]
I started the logging with `giveConsentAll()`, but after calling `removeConsentAll()` the app still continues to send out newly request. And as I see now with activated logging it sends `true` for all user consent.

Please try it yourself. Looks like a bug to me.

```
D/Countly: [Connection Processor] code:[200], response:[{
      “result”: “Success”
    }], response size:[25 B], request: app_key=myapp&timestamp=1647937519367&hour=9&dow=2&tz=60&sdk_version=20.11.10&sdk_name=java-native-android&consent=%7B%22sessions%22%3Atrue%2C%22events%22%3Atrue%2C%22views%22%3Atrue%2C%22location%22%3Atrue%2C%22crashes%22%3Atrue%2C%22attribution%22%3Atrue%2C%22users%22%3Atrue%2C%22push%22%3Atrue%2C%22star-rating%22%3Atrue%2C%22remote-config%22%3Atrue%2C%22apm%22%3Atrue%2C%22feedback%22%3Atrue%7D&device_id=d2e63c33-66f0-4ff0-9180-d0e971e6adc0
```

**Comment by AshStefanOltmann** [comment]
I added it with `api("ly.count.android:sdk:20.11.10")` to gradle.

Thats my source:
```
interface StatisticLogger {

    fun start()

    fun stop()

    fun logViewShown(
        viewName: String
    )

    fun logEvent(
        category: String,
        action: String,
        value: Int? = null
    )
}

class AndroidStatisticLogger(
    private val application: Application,
    private val installId: String
) : StatisticLogger {

    private var active = false

    private var initialized = false

    private var lastScreenName: String? = null

    override fun start() {

        if (active)
            return

        try {

            if (!initialized) {

                val config = CountlyConfig(
                    application,
                    STATISTICS_APP_KEY,
                    STATISTICS_SERVER_URL
                )

                config.setDeviceId(installId)

                config.setRequiresConsent(true)

                config.setLoggingEnabled(true)

                Countly.sharedInstance().init(config)

                Log.info("Countly initialized.")

                initialized = true
            }

            Countly.sharedInstance().consent().giveConsentAll()

            active = true

            Log.info("Statistics logging enabled.")

        } catch (ex: Exception) {
            Log.error("Failed to enable statistics logging.", ex)
        }
    }

    private fun checkCountlyInitialized() =
        check(Countly.sharedInstance().isInitialized) { "Countly is not initialized." }

    override fun stop() {

        if (!active)
            return

        active = false

        try {

            checkCountlyInitialized()

            Countly.sharedInstance().consent().removeConsentAll()

            Log.info("Statistics logging disabled.")

        } catch (ex: Exception) {
            Log.error("Failed to disable statistics logging.", ex)
        }
    }

    override fun logViewShown(viewName: String) {

        if (!active)
            return

        try {

            checkCountlyInitialized()

            /**
             * Filter double events. Only send a new event if the screen name changed.
             */
            if (viewName == lastScreenName)
                return

            this.lastScreenName = viewName

            Countly.sharedInstance().views().recordView(viewName)

            Log.debug("[VIEW] $viewName")

        } catch (ex: Exception) {
            Log.error("Failed to record view.", ex)
        }
    }

    override fun logEvent(category: String, action: String, value: Int?) {

        if (!active)
            return

        try {

            checkCountlyInitialized()

            val eventKey = "$category.$action"

            if (value == null)
                Countly.sharedInstance().events().recordEvent(eventKey)
            else
                Countly.sharedInstance().events().recordEvent(eventKey, value)

            Log.debug("[EVENT] $eventKey - $value")

        } catch (ex: Exception) {
            Log.error("Failed to log event.", ex)
        }
    }
}
```

To see the events I created a new requestbin over at https://requestbin.com/

**Comment by AshStefanOltmann** [comment]
@ArtursKadikis 

Ok, yes. After studying the logs I see it writes "will retry" - so it tries once per minute so send that event again, because it's expecting another answer.

I configured requestbin.com to just send back `{ “result”: “Success” }`.

Which return does the Countly SDK expect from the service?

For a start I want to use requestbin because I need to analyze exactly what data will be transfered for legal reasons.

Logcat:
```
2022-03-22 09:57:19.661 10631-10684/com.myapp V/Countly: [onTimer] Calling heartbeat, Activity count:[1]
2022-03-22 09:57:19.662 10631-10684/com.myapp D/Countly: [ModuleSessions] 'updateSessionInternal'
2022-03-22 09:57:19.662 10631-10684/com.myapp D/Countly: [Connection Queue] updateSession
2022-03-22 09:57:19.663 10631-10684/com.myapp V/Countly: [Countly] Returning consent for feature named: [sessions] [false]
2022-03-22 09:57:19.663 10631-10684/com.myapp V/Countly: [Countly] Returning consent for feature named: [attribution] [false]
2022-03-22 09:57:19.664 10631-10684/com.myapp V/Countly: [Connection Queue] tick, Not empty:[true], Has processor:[false], Done or null:[true]
2022-03-22 09:57:19.664 10631-10690/com.myapp I/Countly: [Connection Processor] Starting to run, there are [5] requests stored
2022-03-22 09:57:19.665 10631-10690/com.myapp V/Countly: [Connection Processor] Got picturePath: 
2022-03-22 09:57:19.665 10631-10690/com.myapp V/Countly: [Connection Processor] Using HTTP GET
2022-03-22 09:57:19.798 10631-10690/com.myapp V/Countly: [Connection Processor] Using HTTP POST: [false] forced:[false] length:[false] crash:[false] | Approx data size: [898 B]
2022-03-22 09:57:19.802 10631-10690/com.myapp D/Countly: [Connection Processor] code:[200], response:[{
      “result”: “Success”
    }], response size:[25 B], request: app_key=myapp&timestamp=1647937519367&hour=9&dow=2&tz=60&sdk_version=20.11.10&sdk_name=java-native-android&consent=%7B%22sessions%22%3Atrue%2C%22events%22%3Atrue%2C%22views%22%3Atrue%2C%22location%22%3Atrue%2C%22crashes%22%3Atrue%2C%22attribution%22%3Atrue%2C%22users%22%3Atrue%2C%22push%22%3Atrue%2C%22star-rating%22%3Atrue%2C%22remote-config%22%3Atrue%2C%22apm%22%3Atrue%2C%22feedback%22%3Atrue%7D&device_id=d2e63c33-66f0-4ff0-9180-d0e971e6adc0
2022-03-22 09:57:19.803 10631-10690/com.myapp V/Countly: [Connection Processor] Response does not contain 'result', will retry
```

**Comment by ArtursKadikis** [comment]
Ah, yes, this would be the issue.  The network requests seem to be failing and then it keeps on retrying to send the same request since we don't drop them on a failed request.
The problem with your response might be the quotation marks used. Try the following string:
`{"result":"Success"}`. The SDK expects a JSON object string with the key "result". The status code should also be 200.

**Comment by AshStefanOltmann** [comment]
@ArtursKadikis Thanks. It works now. My issue was actually that I returned a pretty-print JSON with additional white spaces and line breaks. It must be exactly `{"result":"Success"}` and then it works.
