### ISSUE TITLE
Not able to read the remoteConfig value in Android Project

### ISSUE THREAD

**Issue by prachi2905** [Countly/countly-sdk-android#146]
### Expected Behavior

`Countly.sharedInstance().remoteConfig().getValueForKey("test")`  
Expected result - I can get the value which I set on countly server.

### Current Behavior
I am getting Null value.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/63503965/191488852-14dbd33d-622f-4e43-aab5-07b78c5a1994.png)

### Steps to Reproduce (for bugs)
1. No steps, Just Trying to get the value from countly

### More Description

strange fact is - other countly feature is working fine(for example - event, crash report)

### Your Environment
* Countly Android SDK version -- 20.11.12
* Your Android version--12, (SDK- 31)
* Your device- custom emulator
* Any changes you have made to this SDK- NO

**Comment by ArtursKadikis** [comment]
Looks like you set SDK salt does not match what was set on the server side. Therefore there is a checksum mistmatch
