### ISSUE TITLE
Crash Details ignore metric overrides

### ISSUE THREAD

**Issue by aimkey** [Countly/countly-sdk-android#162]
Crash Details ignore metric overrides

### Expected Behavior

Metric overrides get sent with crash details

### Current Behavior

Metric overrides don't get sent with crash details

### Possible Solution

Use the metric overrides that are stored in ConnectionQueue after init when a crash occurs instead of getting individual values from DeviceInfo when building the crash JSON. See CrashDetails.java line 379 in getCrashData -- instead of getting values from DeviceInfo, DeviceInfo.getMetrics should be used with the metricOverride map stored in ConnectionQueue

### Steps to Reproduce (for bugs)

1. Set metric overrides
2. Intentionally crash the app
3. Note the overridden values don't show up on the backend

PR with fix to follow

**Comment by aimkey** [comment]
See #163

**Comment by ArtursKadikis** [comment]
Hello, this has been fixed in 22.09.1.
