### ISSUE TITLE
Where are the event files on the android system?

### ISSUE THREAD

**Issue by avenir-zhang** [Countly/countly-sdk-android#178]
Hello, I can not find the event files on the local disk. If the app exits, how to handle the events that are not sent to backend? save to local disk? 
### Expected Behavior
I can find the event files.

**Comment by ArtursKadikis** [comment]
Hello,

The SDK automatically stores unsent information persistently in Android shared preferences. We do not have our own file for storage

**Comment by avenir-zhang** [comment]
> Hello,
> 
> The SDK automatically stores unsent information persistently in Android shared preferences. We do not have our own file for storage

Is the name of shared preferences Shared_Countly.xml ?
