### ISSUE TITLE
The Countly SDK has Device and Network Abuse policy issues that will block publishing of your app to Play Console in the future

### ISSUE THREAD

**Issue by n0sk** [Countly/countly-sdk-android#409]
We are using Countly SDK in our project and after updating libraries to the latest version, I got this warning message from the app build.gradle file for:

implementation 'ly.count.android:sdk:24.7.3'

The Warning message says: 
ly. count. android:sdk version 24.7.3 has Device and Network Abuse policy issues that will block publishing of your app to Play Console in the future

Inspection info: This library version has policy issues that will block publishing in the Google Play Store.  

Issue id: PlaySdkIndexNonCompliant  

More info: https://developer.android.com/distribute/sdk-index  

Vendor: 
Android Open Source Project Contact: https://groups.google.com/g/lint-dev 
Feedback: https://issuetracker.google.com/issues/new?component=192708

Is this something you are aware of and is this something that will be addressed?

### Your Environment
* Android Studio Version: Ladybug 2024.2.1 Patch 1
* Countly Android SDK version  24.7.3
* I made no changes to the SDK, i just implement it with: implementation 'ly.count.android:sdk:24.7.3'

**Comment by arifBurakDemiray** [comment]
Hello @n0sk,

Thank you for bringing this to our attention. We are aware of the warning related to the Device and Network Abuse policy with Countly SDK version 24.7.3 and its potential impact on Google Play Console publishing. Our team is actively working on addressing this issue, and we will inform you as soon as a resolution is available.

We appreciate your patience and understanding as we work to ensure full compliance with Play Store policies.

Best regards

**Comment by arifBurakDemiray** [comment]
Hello @n0sk, we have resolved this issue with the latest release of the SDK https://github.com/Countly/countly-sdk-android/releases/tag/24.7.5 🙌 .

Thank you for your patience and understanding.
