### ISSUE TITLE
Cannot create Device ID.

### ISSUE THREAD

**Issue by truonguit2010** [Countly/countly-sdk-android#46]
Hi, I have an problem with Countly SDK. Cannot get device id on SamSung Galaxy Y, Android 2.3.3. Why?
No Device ID available yet, skipping request app_key=d63dd2c4e075961fa65e37674a109cfdb7d7eeab&timestamp=1420634252&sdk_version=14.11&begin_session=1&metrics=%7B%22_locale%22%3A%22vi_VN%22%2C%22_app_version%22%3A%224.4.7%22%2C%22_device%22%3A%22GT-S5360%22%2C%22_resolution%22%3A%22320x240%22%2C%22_os_version%22%3A%222.3.6%22%2C%22_os%22%3A%22Android%22%2C%22_carrier%22%3A%22VINAPHONE%22%2C%22_density%22%3A%22LDPI%22%7D

**Comment by derekmoorecountly** [comment]
Rarely some Android devices are known not to provide device ID.. 

In any case can you let me know what you have done step by step in detail?

**Comment by iartem** [comment]
Closing because of no further comments on this
