### ISSUE TITLE
Too many sessions were created by each device.

### ISSUE THREAD

**Issue by rdshoep** [Countly/countly-sdk-android#47]
Hello, contributers:

    I have a problem, the part of devices create two many sessions.
    
    Enveronment:
          countly:14.12
          compileSdkVersion 19
          buildToolsVersion '22'

This is the statisticcal content by countly server in a half day.
Device-------------Total Sessions-----Total Users----New Users
D5833-------------------9,600----------------1------------------0
A 9-----------------------8,741----------------1------------------0
HTC Incredible S------6,645----------------1------------------0
HTC M8w	---------------5,232----------------1------------------0

**Comment by iartem** [comment]
Hi @rdshoep, did you find out what was wrong in your case?

**Comment by iartem** [comment]
Closing because of lack of details
