### ISSUE TITLE
When is the 15.03 release out? Publish artifacts to jcenter?

### ISSUE THREAD

**Issue by dvdh** [Countly/countly-sdk-android#49]
Hi.
We have an enterprise license and I'm upgrading the countly library for our app to the latest version, but the documentation doesn't make it clear to build it from source or what else. (We can only use a released version instead of development tip so we keep track of dependencies)
http://resources.count.ly/v1.0/docs/downloading-sdks

The latest release on this github project is 14.11 released on Nov 7, 2014.
However in https://github.com/Countly/countly-sdk-android/blob/master/sdk/build.gradle
it mentions a newer version 15.03 but it is not available either on jcenter or maven central.

Question 1:
Are you planning to release 15.03 soon?
Question 2:
Are you going to publish artifacts to jcenter or maven central?

Thanks,
David.

**Comment by iartem** [comment]
Hi David,
I've just released 15.04. 15.03 was available all this time as far as I know, did you have problems with

```
buildscript {
    repositories {
        maven {
            url  "http://dl.bintray.com/countly/maven"
        }
    }
}
```

and 

```
dependencies {
    compile 'ly.count.android:sdk:15.04'
}
```

?

**Comment by dvdh** [comment]
There's no mention of any version available at
https://bintray.com/countly/countly/countly-sdk-android/view

Is there a list of the release versions somewhere?

Thanks.

**Comment by iartem** [comment]
Yes, that repository was obsolete. The real one was here https://bintray.com/countly/maven <https://bintray.com/countly/maven> all the time. It’s the one which can be imported from gradle.

**Comment by dvdh** [comment]
I see, thanks!

On Tue, May 19, 2015 at 11:40 AM, Artem Salpagarov <notifications@github.com
> wrote:

> Yes, that repository was obsolete. The real one was here
> https://bintray.com/countly/maven <https://bintray.com/countly/maven> all
> the time. It’s the one which can be imported from gradle.
>

**Comment by iartem** [comment]
You're welcome
