### ISSUE TITLE
Crash Test

### ISSUE THREAD

**Issue by dieskim** [Countly/countly-sdk-android#52]
Hey,

It would be good to add some crash tests as in iOS SDK

Here are some I have used in my Titanium module..

```
public void stackOverflow() {
		  this.stackOverflow();
}
		 		
		public void crashTest(int crashNumber) {
			
			if (crashNumber == 1){
				Log.d(LCAT, "Running crashTest 1");			
				
				stackOverflow();
				
			}else if (crashNumber == 2){
				
				Log.d(LCAT, "Running crashTest 2");
				
				int test = 10/0;
			
			}else if (crashNumber == 3){
				
				Log.d(LCAT, "Running crashTest 3");
				
					Object[] o = null;
					while (true) { o = new Object[] { o }; }
		
				
			}else{
				
				Log.d(LCAT, "Running crashTest 4");
				
				throw new RuntimeException("This is a crash");
			}
		

		}	
```

**Comment by ar2rsawseen** [comment]
You mean like inside SDK?

because there are already crash examples in demo app:
https://github.com/Countly/countly-sdk-android/blob/master/app/src/main/java/ly/count/android/demo/MainActivity.java#L58-L131

**Comment by dieskim** [comment]
Yes - inside the SDK - then the user can use those directly.

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-sdk-android/commit/1ad31563e83b6322f34470bea3b97e24daf6a98b
Thanks for suggestion ;)
