### ISSUE TITLE
problem of Countly.sharedInstance().init

### ISSUE THREAD

**Issue by darkz1984** [Countly/countly-sdk-android#59]
when I use Countly.sharedInstance().init() method,I found a terrible problem

My test server is 192.168.18.19,default port is 80,so I use "http://192.168.18.19",but I tryed for three days ,no event could be send to the server.when I use "http://192.168.18.19:80",and the document is not say this clearly,so I think when there is no port ,can use 80 for default...

**Comment by ar2rsawseen** [comment]
Hello,
I think that 192.168.18.19 is the internal LAN IP address, so if device is not connected to the same LAN, then event's won't be received.

You would need to use your routers external IP address and configure port forwarding to be able to reach your Countly installation

**Comment by iartem** [comment]
@darkz1984, it surely uses 80 as default.

**Comment by darkz1984** [comment]
@ar2rsawseen  I know 192.168.18.19 is the internal LAN IP address,because I just test the countly sdk and countly server in my work computer.  @iartem  I could not get the event when I am not using the server address without the port 80,and suddenly when I add the ':80',I found the events data in mongo. So, I think it's the Java code problen,I think it can be solved by add the 80 port to countly code before using server url.

**Comment by iartem** [comment]
It just cannot be. Can you reproduce it? If you can, it would be great if you could enable logging:
`Countly.sharedInstance().setLoggingEnabled(true).init(...)`
and post error of lines which start from `Got exception while trying to submit event data` here.

**Comment by darkz1984** [comment]
I try and found that is ok.  found that the document is not so clearly,and I'am new in android develop.
Need to add to network permission.
Is there a clear documents of countly??

**Comment by gorkem-cetin** [comment]
All documentation is available on http://resources.count.ly/docs/countly-sdk-for-android

Let us know which part is not clear and need a rewrite and we can help you. 

Thanks for your concern.

**Comment by darkz1984** [comment]
Thank you very much!!
I read the chinese part.
And  because I am a newbie,so much of the document I think is not clearly or not translate clearly.
Such as part:

> http://resources.count.ly/docs/countly-sdk-for-android
> Add Bintray Maven repository

which and add this content to which section is not very clearly.

**Comment by iartem** [comment]
It’s build.gradle file of your app.

**Comment by iartem** [comment]
I'm closing this issue. In case of any problems feel free to contact us at http://support.count.ly
