### ISSUE TITLE
Allow logging of Throwables instead of just Exceptions

### ISSUE THREAD

**Issue by garyp** [Countly/countly-sdk-android#60]
The `Countly.logException(Exception)` method's signature should be changed to `Countly.logException(Throwable)` (maybe update the name too?) to match the API used by Android's `Log` class: http://developer.android.com/reference/android/util/Log.html. This would make it easier to create a `Log` wrapper that logs the `Throwable` to countly before passing it on to Android's `Log`.

**Comment by iartem** [comment]
This is part of our next major overhaul of SDK. Countly now has `.d`, `.i`, `.w`, `.e`, `.wtf` methods with signatures of `(String)`, `(String, Throwable)`. But it's not yet released...

**Comment by dreamcatcha** [comment]
Any ETA on the new SDK?

**Comment by iartem** [comment]
This week alpha, some 3-6 month later GA.

**Comment by geak** [comment]
Any update?

**Comment by ArtursKadikis** [comment]
The development to the new SDK still continues. It is mostly done, but probably will not be available for public access in the next release since we are still testing it.

**Comment by ArtursKadikis** [comment]
Logging throwables is already supported for a few versions.
