### ISSUE TITLE
Add ability to override DeviceInfo methods.

### ISSUE THREAD

**Issue by seftoner** [Countly/countly-sdk-android#70]
Dear developers, please **don't** use **static** methods and classes at all! Instead of static stuff use clean architecture and interfaces. I would be VERY happy if I could write my own DeviceInfo implementation and don't fork countly SDK.

Love countly. Make peace. More flexibility for dev`s.

**Comment by ar2rsawseen** [comment]
Support this approach a lot. Not in the next version though, but that is something that should be definitely considered for.

Not so familiar with Java and Android development, are there best practices for such cases?

**Comment by iartem** [comment]
Actually new sdk has been all implemented around interfaces for modules aka plugins.

**Comment by iartem** [comment]
Anyway, noted, thanks. Closing this.
