### ISSUE TITLE
What is countlySDK supported Https ?

### ISSUE THREAD

**Issue by amibition521** [Countly/countly-sdk-android#71]
###### countlySDK is supported Https ? I am the server is supported,but I don\`t know the App Client should config this content.I can\`t find the document.

**Comment by gorkem-cetin** [comment]
Just use https instead of http in your configuration to reach out to server. It's written under Setting Up SDK (http://resources.count.ly/docs/countly-sdk-for-android#setting-up-sdk)

Countly.sharedInstance().init(this, "https://YOUR_SERVER", "YOUR_APP_KEY").

**Comment by amibition521** [comment]
I understand your mean.I read the document at last. I find a SSl code. What I can  need to add SSL config at the init() function ?

**Comment by amibition521** [comment]
```
Countly.enablePublicKeyPinning(Arrays.asList().init(this, "https://try.count.ly", "c4608d0a021b1cef0f8cb031f51200e9cbe48dd4");
```

**Comment by iartem** [comment]
I'm sorry I don't get what you mean. We have all that in docs. To enable pinning you need to call this:
http://resources.count.ly/docs/countly-sdk-for-android#section-how-can-i-enable-pinning-of-public-key-of-ssl-certificate-for-extra-security-
