### ISSUE TITLE
Show which ROM in crash report.

### ISSUE THREAD

**Issue by jcgruenhage** [Countly/countly-sdk-android#75]
I have about a thousand crashes that I am sure are caused because the user is using Copperhead OS or something like that, but I can't know for sure, because countly doesn't tell me which ROM is used on the device, only the Android version.

**Comment by gorkem-cetin** [comment]
You can send custom data via SDK which includes ROM name (`Build.DISPLAY`) and it will be shown in your crash data. Below is a sample screenshot.

<img width="1129" alt="custom" src="https://cloud.githubusercontent.com/assets/1757036/26146497/11583850-3af9-11e7-8b61-adf3bcfd2f04.png">

To do this, please visit: http://resources.count.ly/docs/countly-sdk-for-android#section-adding-a-custom-key-value-segment-to-a-crash-report

**Comment by jcgruenhage** [comment]
Thanks for your quick answer, I'll check that out :)
