### ISSUE TITLE
Is the checking of app crawler in ConnectionProcessor a bug?

### ISSUE THREAD

**Issue by LyndonChin** [Countly/countly-sdk-android#77]
Should it be:
```java
!(Countly.sharedInstance().isDeviceAppCrawler() && Countly.sharedInstance().ifShouldIgnoreCrawlers())
```
int https://github.com/Countly/countly-sdk-android/blob/master/sdk/src/main/java/ly/count/android/sdk/ConnectionProcessor.java#L203

**Comment by ArtursKadikis** [comment]
Yep, that's a bug and your recommendation is correct. Thank you for finding it!
