### ISSUE TITLE
Why not use TextUtils.join to join events strings?

### ISSUE THREAD

**Issue by LyndonChin** [Countly/countly-sdk-android#78]
Use `TextUtils.join(strings, delimiter)` instead of `CountlyStore#join`

**Comment by LyndonChin** [comment]
`URLUtil.isValidUrl` is better than `Countly#isValidURL`

**Comment by iartem** [comment]
Yep, you're right. But I don't think we're going to use more of Android utils classes since we're detaching most of code base from Android platform in next version.

**Comment by LyndonChin** [comment]
Thanks for your explanation. 👍
