### ISSUE TITLE
StarRating Dialog property should be customizable for auto implementation.

### ISSUE THREAD

**Issue by abhishekkdubey** [Countly/countly-sdk-android#79]
Well, current SDK star rating dialog is auto cancelable which produce an issue like it's not appearing to user sometimes like:
#1. While auto switching activity without user interaction.(Partially appeared to foreground).
#2 When User Interaction on first screen is too high.

**Comment by abhishekkdubey** [comment]
@gorkem-cetin , Need to replace Rating Dialog with Rating Activity with Dialog theme in SDK, And also provide method to customize property of dialog theme like auto cancelled flag.

**Comment by gorkem-cetin** [comment]
@abhishekkdubey would be great if you could provide us with your PR. possible? :)

**Comment by ArtursKadikis** [comment]
Added functionality that should help work around those issues.
