### ISSUE TITLE
What happened when add event to a full queue?

### ISSUE THREAD

**Issue by tianlin** [Countly/countly-sdk-android#80]
In https://resources.count.ly/docs/sdk-development-guide, it saids "In case of reaching this limit, SDK should remove older queries and insert new ones. The default limit can change from SDK needs, but suggested limit is 1000 queries.". But in android sdk, it drop new one when queue is full. Is it correct?

   /**
     * Adds a custom event to the local store.
     * @param event event to be added to the local store, must not be null
     */
    void addEvent(final Event event) {
        final List<Event> events = eventsList();
        if (events.size() < MAX_EVENTS) {
            events.add(event);
            preferences_.edit().putString(EVENTS_PREFERENCE, joinEvents(events, DELIMITER)).commit();
        }
    }

**Comment by iartem** [comment]
SDK guide states behaviour for new requests rather than events if I'm not mistaken. 

But yes, parsing / dropping in a JSON string of 1000-something events long is rather expensive. So Current SDK version just drops new coming events.

**Comment by tianlin** [comment]
ok,thx
