### ISSUE TITLE
Avoid exposing play-services-gcm library as transitive

### ISSUE THREAD

**Issue by tluksa** [Countly/countly-sdk-android#84]
Hi,
In my project i use few google play services libraries. Because countly sdk-messaging app includes 'com.google.android.gms:play-services-gcm' I'm getting errors that 'play-services-base' library is used with different versions.

Solution would be to update gradle plugin to version '3.0.1' and use 'implementation' keyword instead of 'compile'. In this way, gcm library won't be exposed to project.

**Comment by iartem** [comment]
We've updated Gradle & Android Studio in latest 18.04 release, so it's resolved.
