### ISSUE TITLE
Question about GDPR consent behavior

### ISSUE THREAD

**Issue by bhavya625** [Countly/countly-sdk-android#87]
When the user said `No` to Countly tracking to maintain GDPR compliance, the `LastSeen` for that user is still being updated whenever the app is launched. 

### Expected Behavior
`LastSeen` shouldn't be updated when the users say don't track me.

### Current Behavior
`LastSeen` is updated whenever the app is launched.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/26290795/39594646-461d133e-4edb-11e8-8c95-64c2e302107f.png)

### Your Environment

* Countly Android SDK version - 18.04
* Your Android version - 8.0
* Your device - Galaxy S8+

**Comment by ArtursKadikis** [comment]
Could you show how you initialize Countly and disable tracking?

**Comment by bhavya625** [comment]
I've created a Xamaring binding using this SDK
**Initialization:**
```
Countly.SharedInstance().Init(this, "https://cfainstitute.count.ly", countlyApiKey)
                   .EnableCrashReporting()
                   .SetRequiresConsent(true);
```
**Disable Tracking:**
```
static readonly string[] CountlyFeatures =
        {
            Countly.CountlyFeatureNames.Sessions,
            Countly.CountlyFeatureNames.Events,
            Countly.CountlyFeatureNames.Views,
            Countly.CountlyFeatureNames.Location,
            Countly.CountlyFeatureNames.Crashes,
            Countly.CountlyFeatureNames.Attribution,
            Countly.CountlyFeatureNames.Users,
            Countly.CountlyFeatureNames.Push,
            Countly.CountlyFeatureNames.StarRating
        };
Countly.SharedInstance().RemoveConsent(CountlyFeatures);
```

**Comment by bhavya625** [comment]
We found a fix for this. We were setting the `Name` to `null` which is causing the `lastSeen` being updated. Closing this issue. Thanks!
