### ISSUE TITLE
Cannot get Device Id when there is another OpenUDID service

### ISSUE THREAD

**Issue by asher-y-ma** [Countly/countly-sdk-android#89]
Cannot get Device Id, when there is another app is installed on my phone. That app has a service:

        <service
            android:name="cn.com.bsfit.android.collection.FingerprintService">

            <intent-filter>

                <action
                    android:name="org.OpenUDID.GETUDID" />
            </intent-filter>
        </service>

As I uninstalled that app, I can get device id correctly.

**Comment by ArtursKadikis** [comment]
Latest release should not have this issue.
