### ISSUE TITLE
Https extra header

### ISSUE THREAD

**Issue by SimonCailleaux** [Countly/countly-sdk-android#90]
Hello, 

I installed Countly (community version) to my server with https configuration.

I want to pass an extra header to my resquest and I don't see any possibility with the sdk. Is there a way to do this ?

Thanks

**Comment by ArtursKadikis** [comment]
What kind of thing do you want to add?
Currently there is no way of adding custom headers to requests.

**Comment by SimonCailleaux** [comment]
In Kotlin, I'm able to do this kind of thing with okHttp : 

request = Request.Builder().url(url)
                 .addHeader(headerName, headerKey)
                 .build()

And I want to do the same because we are using this header to secure a bit more our servers.

**Comment by ArtursKadikis** [comment]
The upcomming release will have functionality to add custom key/value pairs,
