### ISSUE TITLE
Support manual session handling same as iOS

### ISSUE THREAD

**Issue by dockusan** [Countly/countly-sdk-android#91]
Is there any plan for support manual session handling the same as iOS? https://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-manual-session-handling

I want to check sessions on a specific screen, not for the whole application.

**Comment by iartem** [comment]
It's implemented in https://github.com/Countly/countly-sdk-android/tree/next. You can already use it for non-production purposes, yet it still lacks some features.

**Comment by dockusan** [comment]
Thank you. But I'm using for our company product, so can I know when is already for the stable version release?

**Comment by gorkem-cetin** [comment]
We suggest you test it, as it has been and is being tested on our side and is used by production apps already. However there are a few features not implemented yet (e.g GDPR).

**Comment by dockusan** [comment]
Ok. I'll try.
