### ISSUE TITLE
One of endEvent's overloaded methods has a problem

### ISSUE THREAD

**Issue by ecarxapp** [Countly/countly-sdk-android#92]
The last two parameters of 'Countly#endEvent(String, String, Map, int, double)' are never used! See below.
![_0aa1d2fe-df36-4251-94ef-7dd1b4a8b209](https://user-images.githubusercontent.com/46699747/53940520-dddba980-40f0-11e9-818e-250a7724ea6d.png)

**Comment by ArtursKadikis** [comment]
Thank you for noticing this.

**Comment by ArtursKadikis** [comment]
Fixed in 19.02.1
