### ISSUE TITLE
If didn't init with an UDID the Demo will be crash

### ISSUE THREAD

**Issue by carlos-wong** [Countly/countly-sdk-android#94]
I am try the Demo, after setup the server url and appkey. the App is crash after start
### Expected Behavior

the demo should be work fine after setup the server url and appkey

### Current Behavior

java.lang.RuntimeException: Unable to start activity ComponentInfo{ly.count.android.demo/ly.count.android.demo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### Possible Solution

if I am init with my custom UDID the countly instance will be init fine. Or if I am disable         Countly.sharedInstance().setRequiresConsent(true); when frist time run, wait the UDID created then reenable         Countly.sharedInstance().setRequiresConsent(true); the App also work fine

### Steps to Reproduce (for bugs)

1.edit the COUNTLY_SERVER_URL and COUNTLY_APP_KEY
2.Run
3.
4.

### Your Environment

* Countly Android SDK version
19.02
* Your Android version
9.0
* Your device
mix2
* Any changes you have made to this SDK
no

**Comment by ArtursKadikis** [comment]
Problem noted

**Comment by chasel** [comment]
me too

**Comment by ArtursKadikis** [comment]
This issues should be fixed
