### ISSUE TITLE
Limit Countly to transmit data via WiFi only

### ISSUE THREAD

**Issue by molmutius** [Countly/countly-sdk-android#95]
Assume there are users with limited available mobile bandwidth and data plans. For those users we would like to limit data consumed on their mobile connection and only send Countly events and crash reports when they are connected to a WiFi network.

Do you have any plans to integrate such a feature into the Countly Android SDK?

**Comment by ArtursKadikis** [comment]
Currently there is no such feature, but we might implement it in the future. But please use our slack channel of forum to inquire about additional features.
