### ISSUE TITLE
Native modules don't build

### ISSUE THREAD

**Issue by aimkey** [Countly/countly-sdk-android#96]
Getting "SIMPLE: Error configuring" when trying to build any of the native modules from a fresh clone.

Using Android Studio 3.4, NDK 19.2.5345600

Which NDK version do you guys recommend?

**Comment by pembeci** [comment]
Strange. I have Studio 3.3, NDK is same and fresh clone is just built without problems on Linux. Are there any other info when you switch to text view for build gradle output? For sdk-native we actually needed to build the cpp-precompilation part outside of Studio with an older NDK but this shouldn't affect Android Studio build.

**Comment by pembeci** [comment]
May be you are experiencing this: `CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set`. The workaround is installing ninja or creating a symbolic link to its executable in Android SDK from a path folder (i.e `/usr/bin`).

**Comment by aimkey** [comment]
Ninja is installed with CMake. I added <sdk_location>/cmake/3.10.2.4988404/bin to PATH and the issue is now fixed. This is an Android Studio bug -- I updated CMake via the UI yesterday and it broke everything. Thanks for the help.

**Comment by pembeci** [comment]
I agree this should be handled by Android Studio in some manner. Glad it was solved.
