### ISSUE TITLE
Changing "Save Location" may lead to crash

### ISSUE THREAD

**Issue by dirtygardner** [Countly/countly-sdk-android#97]
ScreenCam-2.0.3-fdroid on SAMSUNG-SM-G530A_Android-5.1.1

[change "Save Location" to custom path, e.g. `/storage/emulated/0/Download`;
(Go to VIDEOS)⇒("Unfortunately, Screencam has stopped.")]

**SOLUTION**=change "Save Location" to default path, e.g. `/storage/emulated/0/screenrecorder`

**Comment by ArtursKadikis** [comment]
Hello, how is this related to the Countly SDK?

**Comment by dirtygardner** [comment]
Mistake, please delete.
