### ISSUE TITLE
hello, can I set the source from sdk?

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-sdk-android#98]
I found an attribute named 'source' from countly web page. can I set it's value manual?
![image](https://user-images.githubusercontent.com/2630290/64000162-b877a780-cb37-11e9-9ea1-0627ca92ff0b.png)

**Comment by iartem** [comment]
In current version it's rather impossible, but you can always extend SDK and replace [these lines](https://github.com/Countly/countly-sdk-android/blob/master/sdk/src/main/java/ly/count/android/sdk/DeviceInfo.java#L217) with your code.
